### ISSUE TITLE
Persist user's theme preference through local storage

### ISSUE THREAD

**Issue by xypnox** [lttkgp/falcon#32]
> I like this in general! IMO, we should also persist the user preference in localstorage. In cases where I'm someone who uses the OS light mode because it feels better, but would prefer dark mode for websites and specifically, LTTKGP. ( I don't think anyone goes the other way round though :laughing: ) 
> \- @ghostwriternr 

[As requested here](https://github.com/lttkgp/falcon/pull/31#pullrequestreview-442611331)

**Comment by sahil-shubham** [comment]
Hey, I would like to work on this. Is it available?

**Comment by ghostwriternr** [comment]
Go for it @sahil-shubham! 😄
