### ISSUE TITLE
Video page renders well on chrome but some issues on firefox. Screenshot1[Firefox] , Screenshot2[Chrome]. Control bar is kind of half hidden in firefox

### ISSUE THREAD

**Issue by rava-dosa** [lttkgp/falcon#43]
![Firefox Render](https://i.imgur.com/vWuXgcD.png)

![Chrome Render](https://i.imgur.com/gAoKW61.png)

**Comment by xypnox** [comment]
@rava-dosa Can you share a few details:

- The resolution of the monitor
- The window size and 
- The zoom level of the website

Also if possible can you share the layout bounds (length x height) of the parent HTML tag? (available in devtools)

This information will help us in pinpointing which media queries are at fault, also we can replicate this as well.

**Comment by rava-dosa** [comment]
- 1366 X 768
- 1366 X 768
- 100%
