### ISSUE TITLE
Application not working in Netlify https://beta.lttkgp.com/

### ISSUE THREAD

**Issue by ZubierAbd** [lttkgp/falcon#48]
![image](https://user-images.githubusercontent.com/34255944/93726257-00be9900-fb83-11ea-8b93-de6e362aafe0.png)

Have tried in multiple browsers. App runs locally but not on Netlify.

**Comment by ghostwriternr** [comment]
Hi @ZubierAbd! The URL to the live version is https://lttkgp.com. is this what you're looking for?

**Comment by ZubierAbd** [comment]
Yes thanks. I was going through the readme.md links trying to fix an issue. Let me close the issue then.
